### ISSUE TITLE
Tests for exercise: binary-search-tree do not handle missing bst nodes, causing panic

### ISSUE THREAD

**Issue by tapank** [exercism/xgo#667]
The tests for binary-search-tree exercise expect the actual bst (binary search tree) structure to match the expected bst, and checks for the correctness of the data in each node. However, if a node in the actual bst is missing, causing the test to panic. For example:

```
$ go test
--- FAIL: TestInsertingMore (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x8116026]

goroutine 23 [running]:
testing.tRunner.func1(0x1857c800)
	/usr/local/go/src/testing/testing.go:622 +0x226
panic(0x8136280, 0x81cf728)
	/usr/local/go/src/runtime/panic.go:489 +0x22a
_/home/tapan/exercism/go/binary-search-tree.TestInsertingMore(0x1857c800)
	/home/tapan/exercism/go/binary-search-tree/binary_search_tree_test.go:82 +0x56
testing.tRunner(0x1857c800, 0x8155f74)
	/usr/local/go/src/testing/testing.go:657 +0x7e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x242
exit status 2
FAIL	_/home/tapan/exercism/go/binary-search-tree	0.010s
```

This can be reproduced by the following solution to this exercise, where a part of the code that generates the right nodes has been commented out, which results in incomplete bst. (The correct solution can be found here: http://exercism.io/submissions/4eea66bfd42845aa89ec39d606a6624f)

```
package binarysearchtree

const testVersion = 1

type SearchTreeData struct {
	left  *SearchTreeData
	data  int
	right *SearchTreeData
}

func Bst(n int) *SearchTreeData {
	return &SearchTreeData{data: n}
}

func (bst *SearchTreeData) Insert(n int) {
	switch {
	case n <= bst.data:
		if bst.left != nil {
			(*bst).left.Insert(n)
			return
		}
		(*bst).left = Bst(n)
	//case n > bst.data:
	//	if bst.right != nil {
	//		(*bst).right.Insert(n)
	//		return
	//	}
	//	(*bst).right = Bst(n)
	}
}

func (bst *SearchTreeData) MapString(f func(int) string) (sl []string) {
	if bst.left != nil {
		sl = append((*bst).left.MapString(f), sl...)
	}
	sl = append(sl, f(bst.data))
	if bst.right != nil {
		sl = append(sl, (*bst).right.MapString(f)...)
	}
	return
}

func (bst *SearchTreeData) MapInt(f func(int) int) (sl []int) {
	if bst.left != nil {
		sl = append((*bst).left.MapInt(f), sl...)
	}
	sl = append(sl, bst.data)
	if bst.right != nil {
		sl = append(sl, (*bst).right.MapInt(f)...)
	}
	return
}
```

## Expected behavior:

If the actual bst generated by the solution program is missing a node, the test should fail (but not panic) and report the issue correctly.

**Comment by robphoenix** [comment]
closed by #668
